### PR TITLE
ARM7 and Z80 versions of Aplib depacker

### PR DESCRIPTION
**Pull request by Dwedit**
Hello, long time fan of APLib.
I wrote a couple of decompressors for it for Z80 and ARM, let me know if you'd like to add them.
The ARM one is well tested, the Z80 one not so much.

### CODE REVIEW

**Comment by emmanuel-marty** [comment]
Thanks, much appreciated! I might replace or supplement your Z80 decompressor by a well-tested one from [introspec](https://github.com/specke) if he contributes it. The ARM7TDMI depacker will be pretty neat for bootstrapping code and the like

**Comment by asiekierka** [comment]
@Dwedit I cannot find a clear licensing statement, so I'd like to clarify - what is the license on this copy of the decompressor code? Is it the same as aPUltra (zlib), as Loopy's PocketNES (public domain), or is it a different license altogether?

**Comment by Dwedit** [comment]
I'll consider the ARM7TDMI and Z80 versions to be public domain.

**Comment by specke** [comment]
For what is worth, I started to appreciate more the preference that many people have for explicit software licenses.

In that spirit, what do you think, @Dwedit, maybe we can consider adding an explicit license to these decompressors? I would be happy with anything that requires attribution but nothing else, so anything like MIT or zlib or whatever is the correct version of CC would work fine for me.

**Comment by asiekierka** [comment]
I personally use either Creative Commons Zero (which is a public domain declaration with kilobytes of legalese which approximate public domain-style rights for jurisdictions which do not allow placing things in the public domain on one's own), zlib (license with attribution required on source distributions, but not on binary ones) or MIT-0 (license with no attribution required) in this scenario, in order of preference.

**Comment by Dwedit** [comment]
ZLIB license sounds good.

**Pull request merged**
